# -*- coding: utf-8 -*-
"""voiceai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uys0hPILf3RQVK5EfIuKhomM3OyMRvj
"""

# Voice AI Project - Complete Implementation
# Copy and paste this entire cell into Google Colab and run

# Install required packages
!pip install -q gradio transformers torch gtts SpeechRecognition pydub soundfile

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from gtts import gTTS
import speech_recognition as sr
import json
import random
from datetime import datetime
import tempfile
import os

# ================================
# DATA STRUCTURES
# ================================

class ConversationHistory:
    """Stores conversation context"""
    def __init__(self, max_history=10):
        self.messages = []
        self.max_history = max_history

    def add(self, role, content):
        self.messages.append({
            "role": role,
            "content": content,
            "timestamp": datetime.now().isoformat()
        })
        if len(self.messages) > self.max_history:
            self.messages.pop(0)

    def get_context(self):
        return "\n".join([f"{m['role']}: {m['content']}" for m in self.messages[-5:]])

class Flashcard:
    """Represents a single flashcard"""
    def __init__(self, question, answer, topic="General"):
        self.question = question
        self.answer = answer
        self.topic = topic
        self.reviews = 0
        self.last_reviewed = None

class FlashcardDeck:
    """Manages collection of flashcards"""
    def __init__(self):
        self.cards = []

    def add_card(self, question, answer, topic="General"):
        self.cards.append(Flashcard(question, answer, topic))

    def get_random_card(self):
        if not self.cards:
            return None
        return random.choice(self.cards)

class QuizQuestion:
    """Represents a quiz question"""
    def __init__(self, question, correct_answer, options=None):
        self.question = question
        self.correct_answer = correct_answer
        self.options = options or []
        self.user_answer = None
        self.is_correct = None

class Quiz:
    """Manages quiz sessions"""
    def __init__(self, topic, num_questions=5):
        self.topic = topic
        self.questions = []
        self.current_index = 0
        self.score = 0
        self.total_questions = num_questions

    def add_question(self, question):
        self.questions.append(question)

    def get_current_question(self):
        if self.current_index < len(self.questions):
            return self.questions[self.current_index]
        return None

    def submit_answer(self, answer):
        current = self.get_current_question()
        if current:
            current.user_answer = answer
            current.is_correct = answer.lower().strip() == current.correct_answer.lower().strip()
            if current.is_correct:
                self.score += 1
            self.current_index += 1
            return current.is_correct
        return None

# ================================
# VOICE AI SYSTEM
# ================================

class VoiceAISystem:
    """Main Voice AI System"""

    def __init__(self):
        print("🚀 Initializing Voice AI System...")

        # Load IBM Granite model
        model_name = "ibm-granite/granite-3.0-2b-instruct"
        print(f"📥 Loading {model_name}...")

        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="auto"
        )

        # Initialize components
        self.conversation = ConversationHistory()
        self.flashcard_deck = FlashcardDeck()
        self.current_quiz = None
        self.recognizer = sr.Recognizer()

        print("✅ Voice AI System ready!")

    def generate_response(self, prompt, max_length=300):
        """Generate AI response using IBM Granite"""
        system_prompt = """You are a friendly AI tutor. Explain things simply as if talking to a 10-year-old.
Use stories and examples. Keep responses conversational and clear. Be patient and encouraging."""

        full_prompt = f"{system_prompt}\n\nUser: {prompt}\nAssistant:"

        inputs = self.tokenizer(full_prompt, return_tensors="pt").to(self.model.device)

        outputs = self.model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=self.tokenizer.eos_token_id
        )

        response = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        response = response.split("Assistant:")[-1].strip()

        return response

    def text_to_speech(self, text):
        """Convert text to speech (slow pace)"""
        tts = gTTS(text=text, lang='en', slow=True)

        with tempfile.NamedTemporaryFile(delete=False, suffix='.mp3') as fp:
            temp_path = fp.name
            tts.save(temp_path)

        return temp_path

    def speech_to_text(self, audio_file):
        """Convert speech to text"""
        try:
            with sr.AudioFile(audio_file) as source:
                audio = self.recognizer.record(source)
                text = self.recognizer.recognize_google(audio)
                return text
        except Exception as e:
            return f"Error: Could not understand audio - {str(e)}"

    def explain_topic(self, topic, use_story=False):
        """Explain a topic simply"""
        story_prompt = "Explain using a fun story: " if use_story else ""
        prompt = f"{story_prompt}Explain {topic} to a 10-year-old in simple terms."

        response = self.generate_response(prompt)
        self.conversation.add("User", topic)
        self.conversation.add("Assistant", response)

        return response

    def generate_flashcards(self, topic, num_cards=5):
        """Generate flashcards for a topic"""
        prompt = f"Generate {num_cards} question-answer pairs about {topic} for revision. Format: Q: question\\nA: answer"
        response = self.generate_response(prompt, max_length=500)

        # Parse flashcards
        lines = response.split('\n')
        current_q = None

        for line in lines:
            line = line.strip()
            if line.startswith('Q:'):
                current_q = line[2:].strip()
            elif line.startswith('A:') and current_q:
                answer = line[2:].strip()
                self.flashcard_deck.add_card(current_q, answer, topic)
                current_q = None

        return f"✅ Generated {len(self.flashcard_deck.cards)} flashcards for {topic}!"

    def start_quiz(self, topic, num_questions=5):
        """Start an oral quiz"""
        self.current_quiz = Quiz(topic, num_questions)

        prompt = f"Generate {num_questions} simple quiz questions about {topic} with short answers. Format: Q: question\\nA: answer"
        response = self.generate_response(prompt, max_length=600)

        lines = response.split('\n')
        current_q = None

        for line in lines:
            line = line.strip()
            if line.startswith('Q:'):
                current_q = line[2:].strip()
            elif line.startswith('A:') and current_q:
                answer = line[2:].strip()
                self.current_quiz.add_question(QuizQuestion(current_q, answer))
                current_q = None

        first_q = self.current_quiz.get_current_question()
        return f"🎯 Quiz started on {topic}!\n\nQuestion 1: {first_q.question if first_q else 'No questions generated'}"

    def answer_quiz_question(self, answer):
        """Submit quiz answer"""
        if not self.current_quiz:
            return "⚠️ No active quiz. Start a quiz first!"

        is_correct = self.current_quiz.submit_answer(answer)

        if is_correct is None:
            result = f"🏆 Quiz Complete!\n\nScore: {self.current_quiz.score}/{self.current_quiz.total_questions}"
            self.current_quiz = None
            return result

        feedback = "✅ Correct!" if is_correct else f"❌ Wrong. Correct answer: {self.current_quiz.questions[self.current_quiz.current_index-1].correct_answer}"

        next_q = self.current_quiz.get_current_question()
        if next_q:
            return f"{feedback}\n\nQuestion {self.current_quiz.current_index + 1}: {next_q.question}"
        else:
            result = f"{feedback}\n\n🏆 Quiz Complete!\n\nScore: {self.current_quiz.score}/{self.current_quiz.total_questions}"
            self.current_quiz = None
            return result

# ================================
# GRADIO INTERFACE
# ================================

# Initialize system
ai_system = VoiceAISystem()

def read_text_aloud(text):
    """Feature 1: Read text aloud"""
    audio_path = ai_system.text_to_speech(text)
    return audio_path, "🔊 Text converted to speech!"

def voice_command(audio):
    """Feature 2 & 7: Voice command processing"""
    if audio is None:
        return "⚠️ No audio detected", None

    text = ai_system.speech_to_text(audio)
    response = ai_system.generate_response(text)
    audio_path = ai_system.text_to_speech(response)

    return f"You said: {text}\n\nResponse: {response}", audio_path

def explain_simply(topic, use_story):
    """Features 4, 5, 6: Explain topics"""
    response = ai_system.explain_topic(topic, use_story)
    audio_path = ai_system.text_to_speech(response)
    return response, audio_path

def create_flashcards(topic, num_cards):
    """Feature 8: Generate flashcards"""
    result = ai_system.generate_flashcards(topic, num_cards)
    card = ai_system.flashcard_deck.get_random_card()

    if card:
        audio_path = ai_system.text_to_speech(f"Question: {card.question}")
        return f"{result}\n\nSample Card:\nQ: {card.question}\nA: {card.answer}", audio_path
    return result, None

def quiz_start(topic, num_questions):
    """Feature 9: Start quiz"""
    result = ai_system.start_quiz(topic, num_questions)
    audio_path = ai_system.text_to_speech(result)
    return result, audio_path

def quiz_answer_text(answer):
    """Submit text answer to quiz"""
    result = ai_system.answer_quiz_question(answer)
    audio_path = ai_system.text_to_speech(result)
    return result, audio_path

def quiz_answer_voice(audio):
    """Submit voice answer to quiz"""
    if audio is None:
        return "⚠️ No audio detected", None

    answer = ai_system.speech_to_text(audio)
    result = ai_system.answer_quiz_question(answer)
    audio_path = ai_system.text_to_speech(result)
    return f"Your answer: {answer}\n\n{result}", audio_path

# Create Gradio Interface
with gr.Blocks(title="Voice AI - Interactive Learning Assistant", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🎙️ Voice AI - Your Personal Learning Assistant")
    gr.Markdown("*Powered by IBM Granite 3.0 2B Instruct*")

    with gr.Tab("📖 Read Aloud"):
        with gr.Row():
            text_input = gr.Textbox(label="Enter text to read aloud", lines=3)
            read_btn = gr.Button("🔊 Read Aloud", variant="primary")
        audio_output1 = gr.Audio(label="Audio Output", type="filepath")
        status1 = gr.Textbox(label="Status")
        read_btn.click(read_text_aloud, inputs=text_input, outputs=[audio_output1, status1])

    with gr.Tab("🎤 Voice Commands"):
        gr.Markdown("*Ask any question using your voice!*")
        audio_input = gr.Audio(label="Record your question", type="filepath", sources=["microphone"])
        voice_btn = gr.Button("🎙️ Process Voice Command", variant="primary")
        response_text = gr.Textbox(label="Response", lines=5)
        audio_output2 = gr.Audio(label="Audio Response", type="filepath")
        voice_btn.click(voice_command, inputs=audio_input, outputs=[response_text, audio_output2])

    with gr.Tab("🧠 Learn & Explain"):
        gr.Markdown("*Get simple explanations for any topic*")
        topic_input = gr.Textbox(label="What do you want to learn?", placeholder="e.g., photosynthesis, black holes, etc.")
        use_story = gr.Checkbox(label="Use story-based explanation", value=False)
        explain_btn = gr.Button("📚 Explain", variant="primary")
        explanation = gr.Textbox(label="Explanation", lines=8)
        audio_output3 = gr.Audio(label="Audio Explanation", type="filepath")
        explain_btn.click(explain_simply, inputs=[topic_input, use_story], outputs=[explanation, audio_output3])

    with gr.Tab("🃏 Flashcards"):
        gr.Markdown("*Generate audio flashcards for revision*")
        with gr.Row():
            flashcard_topic = gr.Textbox(label="Topic", placeholder="e.g., Solar System")
            num_flashcards = gr.Slider(3, 10, value=5, step=1, label="Number of flashcards")
        flashcard_btn = gr.Button("🎴 Generate Flashcards", variant="primary")
        flashcard_result = gr.Textbox(label="Flashcards", lines=6)
        audio_output4 = gr.Audio(label="Sample Flashcard Audio", type="filepath")
        flashcard_btn.click(create_flashcards, inputs=[flashcard_topic, num_flashcards], outputs=[flashcard_result, audio_output4])

    with gr.Tab("🎯 Oral Quiz"):
        gr.Markdown("*Test your knowledge with interactive quizzes*")

        with gr.Row():
            quiz_topic = gr.Textbox(label="Quiz Topic", placeholder="e.g., World Geography")
            quiz_num = gr.Slider(3, 10, value=5, step=1, label="Number of questions")

        start_quiz_btn = gr.Button("🚀 Start Quiz", variant="primary")
        quiz_display = gr.Textbox(label="Quiz", lines=6)
        audio_output5 = gr.Audio(label="Question Audio", type="filepath")

        gr.Markdown("### Answer Options")

        with gr.Row():
            with gr.Column():
                gr.Markdown("**Text Answer**")
                text_answer = gr.Textbox(label="Type your answer", placeholder="Enter answer here")
                submit_text_btn = gr.Button("✍️ Submit Text Answer")

            with gr.Column():
                gr.Markdown("**Voice Answer**")
                voice_answer = gr.Audio(label="Record your answer", type="filepath", sources=["microphone"])
                submit_voice_btn = gr.Button("🎤 Submit Voice Answer")

        quiz_result = gr.Textbox(label="Result", lines=4)
        audio_output6 = gr.Audio(label="Result Audio", type="filepath")

        start_quiz_btn.click(quiz_start, inputs=[quiz_topic, quiz_num], outputs=[quiz_display, audio_output5])
        submit_text_btn.click(quiz_answer_text, inputs=text_answer, outputs=[quiz_result, audio_output6])
        submit_voice_btn.click(quiz_answer_voice, inputs=voice_answer, outputs=[quiz_result, audio_output6])

# Launch the app
demo.launch(debug=True, share=True)

